---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCCoquN+dfhoAoXHvyGUoQENFbgfnW9HVqCZf08HR6mE/EhzzH8o1vQAkS9DXg9cov4K8CSGXDbsq/kzD8doZgWd2oHmSW/OkILKI4L16x8HoeJfY7VekHdcq+wvgM2lpQy3lx/Hh2R928tVNgfnH9y2dMtAegsq9TuFRcWfL5LlBuJBFpwUVUnGrM4b545VQ+yEutM+Nn2OxdmIqzEF/08cHYhOCA5ewLMdFOlp8W7ydx9ZeTK/L5R4MHAkV9NfRV8Tj5p2xMlKpsk1vIo5IVaj8/Dh/epnI+k6qserWIgSO/wB8wDjuuokLOykusk8GBfpqSEpWLf1+vj010qHGh2gcFDEvmQQP5aEK93jSnhrvF10PztC8vPiFGkpM1ramFRriwff0RL+sFBUcm5unzSM//PmGn2cYD1bJIAx1E7xoySzCsCGvqoo4QP9+cjbXoQdq9kdtrGcZ19WNxj2Ulmqaqi/nj/d0omBiO7YkGQczltW4cn0NAk7LIhM5w9HotBsWusbd/MxadIDtfPDPqyBhKoSRlBCUdNB+yGLCbTWZ1xaKzeSlB2tVsmroXHy/TxgirJdGdyRFzRNK8knHGxew3oI9Mw+4dIGKVzvnBdfiQhlrHMwGujGWE7yulC+UEQM1nzWkab/RATlOb97RFYvJtfx9IVP4573Ql2nGwkODex22ySU3OtaCSYURy+5uBFWW2nzOjmJCUDeUs7ir6w9gn0XHPnmPYI
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
